package com.helltar.vusan.tools.youtube

import com.helltar.vusan.tools.Arg
import com.helltar.vusan.tools.Tool
import com.helltar.vusan.tools.ToolSet
import com.helltar.vusan.common.limitTo
import com.helltar.vusan.common.xmlBlock
import com.helltar.vusan.tools.suspendToolGuard
import kotlin.time.Duration.Companion.seconds

private const val MAX_TRANSCRIPT_CHARS = 24_000

class YouTubeTranscriptTools(private val client: YouTubeTranscriptClient) : ToolSet {

    @Tool(YouTubeTranscriptToolDescriptions.READ_TRANSCRIPT, readOnly = true, copiedToSandbox = true)
    suspend fun readYouTubeTranscript(
        @Arg(YouTubeTranscriptToolDescriptions.READ_TRANSCRIPT_QUERY)
        query: String,
    ): String = suspendToolGuard {
        when (val result = client.fetchTranscript(query)) {
            is YtDlpResult.NotFound ->
                """No usable subtitles found for "$query". The video offers no subtitle track at all, so there is nothing to read."""

            is YtDlpResult.TooLarge -> """Subtitles for "$query" are too large to read."""
            is YtDlpResult.AuthRequired -> error("YouTube is asking yt-dlp to sign in. Configure `YT_DLP_COOKIES_FILE` in the bot environment.")
            is YtDlpResult.Failure -> error("Failed to fetch subtitles: ${result.reason}")
            is YtDlpResult.Success -> result.value.render()
        }
    }

    private fun YtDlpTranscript.render(): String {
        val transcript = text.limitTo(MAX_TRANSCRIPT_CHARS)

        return buildString {
            appendLine("YouTube transcript: $title")
            uploader?.let { appendLine("Channel: $it") }
            durationSeconds?.let { appendLine("Duration: ${it.seconds}") }
            sourceUrl?.let { appendLine("Source: $it") }
            appendLine("Subtitle language: $language${if (autoGenerated) " (auto-generated, may misspell names and terms)" else ""}")

            if (transcript.length < text.length) {
                appendLine("Note: only the first part of the video is included; the transcript was cut at $MAX_TRANSCRIPT_CHARS characters.")
            }

            appendLine()
            append(xmlBlock("transcript", transcript))
        }
    }
}
