package com.helltar.vusan.tools.youtube

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
internal data class YtDlpInfo(
    val title: String? = null,
    val track: String? = null,
    val artist: String? = null,
    val uploader: String? = null,
    val channel: String? = null,
    val duration: Double? = null,
    val language: String? = null,
    val width: Int? = null,
    val height: Int? = null,
    @SerialName("webpage_url") val webpageUrl: String? = null,
    @SerialName("filesize_approx") val filesizeApprox: Long? = null,
    // author-provided tracks; the ASR original and its machine translations live in the other map
    val subtitles: Map<String, JsonElement>? = null,
    @SerialName("automatic_captions") val automaticCaptions: Map<String, JsonElement>? = null
)

@Serializable
internal data class YtDlpSearchResult(
    val entries: List<YtDlpSearchEntry>? = null
)

@Serializable
internal data class YtDlpSearchEntry(
    val id: String? = null,
    val url: String? = null,
    @SerialName("webpage_url") val webpageUrl: String? = null
)

class YtDlpTrack(
    val bytes: ByteArray,
    val title: String,
    val performer: String,
    val durationSeconds: Int?,
    val sourceUrl: String?
)

class YtDlpVideo(
    val bytes: ByteArray,
    val title: String,
    val uploader: String?,
    val durationSeconds: Int?,
    val width: Int?,
    val height: Int?,
    val thumbnailBytes: ByteArray?,
    val sourceUrl: String?
)

class YtDlpTranscript(
    val text: String,
    val title: String,
    val uploader: String?,
    val durationSeconds: Int?,
    val language: String,
    val autoGenerated: Boolean,
    val sourceUrl: String?
)

sealed class YtDlpResult<out T> {
    class Success<T>(val value: T) : YtDlpResult<T>()
    object NotFound : YtDlpResult<Nothing>()
    class TooLarge(val sizeBytes: Long) : YtDlpResult<Nothing>()
    object AuthRequired : YtDlpResult<Nothing>()
    class Failure(val reason: String) : YtDlpResult<Nothing>()
}
